<?xml version="1.0" encoding="euc-kr"?>
<!DOCTYPE BookCatalog [
	<!ELEMENT BookCatalog (Book*)>
	<!ELEMENT Book (Title, Author, Year)>
	<!ELEMENT Title (#PCDATA)>
	<!ELEMENT Author (#PCDATA)>
	<!ELEMENT Year (#PCDATA)>
]>

<BookCatalog>
	<Book>
		<Title>XML 프로그래밍</Title>
		<Author>홍성용</Author>
		<Year>2015</Year>
	</Book>
	<Book>
		<Title>이것이 자바다</Title>
		<Author>신용권</Author>
		<Year>2015</Year>
	</Book>
	<Book>
		<Title>파이썬으로 만드는 OpenCV 프로젝트</Title>
		<Author>이세우</Author>
		<Year>2019</Year>
	</Book>
	<Book>
		<Title>컴퓨터 네트워크 프로그래밍 Unix Version</Title>
		<Author>김화종</Author>
		<Year>2004</Year>
	</Book>
	<Book>
		<Title>고구려</Title>
		<Author>김진명</Author>
		<Year>2012</Year>
	</Book>
</BookCatalog>