=== Sanggoe/xml/middleterm_homework/Cuisine.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
		targetNamespace="https://sanggoe.tistory.com"
		xmlns:target="https://sanggoe.tistory.com"
		elementFormDefault="qualified">

	<!-- Attribute Area -->

	<!-- [countries]Cuisine attribute -->
	<attributeGroup name="countriesCuisineAttributeGroup">
		<attribute name="culture" use="required">
			<simpleType>
				<restriction base="string">
					<enumeration value="Asia"/>
					<enumeration value="Europ"/>
					<enumeration value="America"/>
				</restriction>
			</simpleType>
		</attribute>
	</attributeGroup>


	<!-- Cuisine attribute -->
	<attributeGroup name="cuisineAttributeGroup">
		<attribute name="cookingMethod" use="optional">
			<simpleType>
				<restriction base="string">
					<enumeration value="grilled"/>
					<enumeration value="smoked"/>
					<enumeration value="stir-fried"/>
					<enumeration value="boiled"/>
					<enumeration value="small-water-boiled"/>
					<enumeration value="fried"/>
					<enumeration value="steamed"/>
					<enumeration value="rawed"/>
				</restriction>
			</simpleType>
		</attribute>
	</attributeGroup>
	

	<!-- Ingredients attribute -->
	<attributeGroup name="ingredientsAttributeGroup">
		<attributeGroup ref="target:cuisineAttributeGroup"/>
	</attributeGroup>


	<!-- kinds's attribute -->
	<attributeGroup name="kindsAttributeGroup">
		<attribute name="classification" use="optional">
			<simpleType>
				<restriction base="string">
					<!-- vegetables -->
					<enumeration value="leaf"/>
					<enumeration value="stem"/>
					<enumeration value="root"/>
					<enumeration value="lychee"/>
					
					<!-- fruits -->

					<!-- meats -->
					<enumeration value="pork"/>
					<enumeration value="beef"/>
					<enumeration value="chicken"/>
					<enumeration value="egg"/>

					<!-- microbes -->
					<enumeration value="mushroom"/>

					<!-- grain -->
					<enumeration value="wheat"/>
					<enumeration value="rice"/>

					<!-- condiment -->
					<enumeration value="sweety"/>
					<enumeration value="salty"/>
					<enumeration value="sour"/>
					<enumeration value="savory"/>
					<enumeration value="spicy"/>
					<enumeration value="curry"/>
				</restriction>
			</simpleType>
		</attribute>
	</attributeGroup>

	<!-- Attribute Area -->



	<!-- Element Area -->

	<!-- Cuisine element -->
	<element name="Cuisine"> <!-- element -->
		<complexType mixed="true">
			<choice>
				<element name="Ingredients" maxOccurs="unbounded"> <!-- element -->
					<complexType>
						<choice minOccurs="1" maxOccurs="unbounded">
							<element name="vegetables" type="target:KindsType"/>
							<element name="fruits" type="target:KindsType"/>
							<element name="meats" type="target:KindsType"/>
							<element name="microbes" type="target:KindsType"/>
							<element name="seafood" type="target:KindsType"/>
							<element name="fermentedFood" type="target:KindsType"/>
							<element name="oilsAndFats" type="target:KindsType"/>
							<element name="grain" type="target:KindsType"/>
							<element name="condiment" type="target:KindsType"/>
							<element name="water" type="target:KindsType"/>
						</choice>
						<attributeGroup ref="target:ingredientsAttributeGroup"/>
					</complexType>
				</element>
			</choice>
			<attributeGroup ref="target:cuisineAttributeGroup"/>
		</complexType>
	</element>

	<!-- Element Area -->



	<!-- Type Area -->

	<!-- Kinds type -->
	<complexType name="KindsType" mixed="true">
		<choice minOccurs="1" maxOccurs="2">
			<element name="cup" minOccurs="0" type="string"/> <!-- element -->
			<element name="spoon" minOccurs="0" type="string"/> <!-- element -->
			<element name="count" minOccurs="0" type="string"/> <!-- element -->
			<element name="gram" minOccurs="0" type="string"/> <!-- element -->
			<element name="milliliter" minOccurs="0" type="string"/> <!-- element -->
		</choice>
		<attributeGroup ref="target:kindsAttributeGroup"/>				
	</complexType>


	<!-- countries type -->
	<complexType name="countriesType">
		<choice>
			<element ref="target:Cuisine" maxOccurs="unbounded"/>
		</choice>
		<attributeGroup ref="target:countriesCuisineAttributeGroup"/>
	</complexType>
	
	<!-- Type Area -->

	
	
	<!-- Root Element Area -->

	<!-- root element -->
	<element name="CuisineCatalog"> <!-- element -->
		<complexType>
			<sequence>
				<element name="KoreanCuisine" type="target:countriesType"/> <!-- element -->
				<element name="IndianCuisine" type="target:countriesType"/> <!-- element -->
				<element name="ItalianCuisine" type="target:countriesType"/> <!-- element -->
				<element name="AmericanCuisine" type="target:countriesType"/> <!-- element -->
			</sequence>
		</complexType>
	</element>

	<!-- Root Element Area -->
</schema>

=== Sanggoe/xml/middleterm_homework/Cuisine.xml
<?xml version="1.0"?>
<CuisineCatalog xmlns="https://sanggoe.tistory.com"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="https://sanggoe.tistory.com Cuisine.xsd">
	
	<KoreanCuisine culture="Asia">

		<!-- Korean Cuisine 1 -->
		<Cuisine cookingMethod="boiled">김치찌개
			<Ingredients cookingMethod="stir-fried">
				<meats classification="pork">앞다리살
					<cup>1</cup>
					<gram>200</gram>
				</meats>
			</Ingredients>
			<Ingredients cookingMethod="boiled">
				<water>물
					<cup>3</cup>
					<milliliter>600</milliliter>
				</water>
			</Ingredients>
			<Ingredients>
				<fermentedFood>새우젓
					<spoon>1</spoon>
					<gram>20</gram>
				</fermentedFood>
			</Ingredients>
			<Ingredients>
				<fermentedFood>신김치
					<cup>2</cup>
					<gram>400</gram>
				</fermentedFood>
			</Ingredients>
			<Ingredients>
				<condiment classification="salty">간장
					<spoon>1</spoon>
					<gram>10</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<condiment classification="spicy">고춧가루
					<spoon>1</spoon>
					<gram>20</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">마늘
					<spoon>1</spoon>
					<gram>20</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="lychee">청양고추
					<count>2</count>
					<gram>20</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="stem">대파
					<count>2/3</count>
					<gram>20</gram>
				</vegetables>
			</Ingredients>
		</Cuisine>

		<!-- Korean Cuisine 2 -->
		<Cuisine cookingMethod="boiled">소고기뭇국
			<Ingredients>
				<oilsAndFats>식용유
					<spoon>1</spoon>
					<gram>10</gram>
				</oilsAndFats>
			</Ingredients>
			<Ingredients>
				<oilsAndFats>참기름
					<spoon>1</spoon>
					<gram>10</gram>
				</oilsAndFats>
			</Ingredients>
			<Ingredients cookingMethod="stir-fried">
				<meats classification="beef">양지살
					<cup>1</cup>
					<gram>200</gram>
				</meats>
			</Ingredients>
			<Ingredients cookingMethod="stir-fried">
				<vegetables classification="root">무
					<cup>1.5</cup>
					<gram>300</gram>
				</vegetables>
			</Ingredients>
			<Ingredients cookingMethod="boiled">
				<water>물
					<cup>7.5</cup>
					<milliliter>1500</milliliter>
				</water>
			</Ingredients>			
			<Ingredients>
				<vegetables classification="root">마늘
					<spoon>1</spoon>
					<gram>20</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<condiment classification="salty">국간장
					<spoon>2</spoon>
					<gram>20</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<condiment classification="salty">소금
					<spoon>1</spoon>
					<gram>10</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<condiment classification="salty">액젓
					<spoon>2</spoon>
					<gram>20</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<vegetables classification="stem">대파
					<cup>1</cup>
					<gram>80</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="spicy">후추
					<spoon>1</spoon>
					<gram>10</gram>
				</vegetables>
			</Ingredients>
		</Cuisine>

		<!-- Korean Cuisine 3 -->
		<Cuisine cookingMethod="boiled">닭볶음탕
			<Ingredients cookingMethod="boiled">
				<water>물
					<cup>3</cup>
					<milliliter>600</milliliter>
				</water>
			</Ingredients>
			<Ingredients>
				<meats classification="chicken">닭
					<count>1</count>
					<gram>1000</gram>
				</meats>
			</Ingredients>
			<Ingredients>
				<condiment classification="sweety">설탕
					<cup>1/2</cup>
					<gram>70</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">감자
					<count>2</count>
					<gram>270</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">당근
					<count>1/2</count>
					<gram>160</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">양파
					<count>1/2</count>
					<gram>240</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">마늘
					<cup>1/3</cup>
					<gram>45</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<condiment classification="salty">진간장
					<cup>1</cup>
					<gram>190</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<microbes classification="mushroom">표고버섯
					<count>3</count>
					<gram>70</gram>
				</microbes>
			</Ingredients>
			<Ingredients>
				<microbes classification="mushroom">새송이버섯
					<count>2</count>
					<gram>50</gram>
				</microbes>
			</Ingredients>
			<Ingredients>
				<condiment classification="spicy">고운 고춧가루
					<cup>1/3</cup>
					<gram>30</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<condiment classification="spicy">굵은 고춧가루
					<cup>1/2</cup>
					<gram>45</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<vegetables classification="lychee">청양고추
					<count>4</count>
					<gram>40</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="stem">대파
					<count>3</count>
					<gram>160</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="spicy">후추
					<spoon>1/2</spoon>
					<gram>5</gram>
				</vegetables>
			</Ingredients>
		</Cuisine>

		<!-- Korean Cuisine 4 -->
		<Cuisine cookingMethod="steamed">계란찜
			<Ingredients>
				<meats classification="egg">계란
					<count>6</count>
					<gram>324</gram>
				</meats>
			</Ingredients>
			<Ingredients>
				<fermentedFood>새우젓
					<spoon>1</spoon>
					<gram>15</gram>
				</fermentedFood>
			</Ingredients>
			<Ingredients>
				<condiment classification="sweety">설탕
					<spoon>1/2</spoon>
					<gram>5</gram>
				</condiment>
			</Ingredients>
			<Ingredients cookingMethod="boiled">
				<water>물
					<cup>1/3</cup>
					<milliliter>60</milliliter>
				</water>
			</Ingredients>
			<Ingredients>
				<vegetables classification="stem">대파
					<count>1/3</count>
					<gram>40</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<oilsAndFats>참기름
					<spoon>1</spoon>
					<milliliter>15</milliliter>
				</oilsAndFats>
			</Ingredients>
			<Ingredients>
				<grain>깨
					<spoon>1/2</spoon>
					<gram>5</gram>
				</grain>
			</Ingredients>			
			<Ingredients>
				<vegetables classification="lychee">청양고추
					<count>1</count>
					<gram>10</gram>
				</vegetables>
			</Ingredients>	
			<Ingredients>
				<vegetables classification="spicy">후추
					<spoon>1/2</spoon>
					<gram>5</gram>
				</vegetables>
			</Ingredients>
		</Cuisine>

		
		<!-- Korean Cuisine 5 -->
		<Cuisine cookingMethod="steamed">김치전
			<Ingredients>
				<fermentedFood>신김치
					<cup>2</cup>
					<gram>260</gram>
				</fermentedFood>
			</Ingredients>
			<Ingredients>
				<condiment classification="sour">식초
					<spoon>1</spoon>
					<gram>5</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<vegetables classification="lychee">청양고추
					<count>2</count>
					<gram>20</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="stem">대파
					<count>2/5</count>
					<gram>40</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<condiment classification="spicy">고운 고춧가루
					<spoon>1</spoon>
					<gram>6</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<condiment classification="sweety">설탕
					<spoon>1/2</spoon>
					<gram>6</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<condiment classification="savory">다시다
					<spoon>1/2</spoon>
					<gram>5</gram>
				</condiment>
			</Ingredients>
			<Ingredients>
				<grain classification="wheat">부침가루
					<spoon>2</spoon>
					<gram>220</gram>
				</grain>
			</Ingredients>
			<Ingredients cookingMethod="boiled">
				<water>물
					<cup>1.7</cup>
					<milliliter>300</milliliter>
				</water>
			</Ingredients>
			<Ingredients>
				<oilsAndFats>식용유
					<cup>1</cup>
				</oilsAndFats>
			</Ingredients>
		</Cuisine>
	</KoreanCuisine>


	<IndianCuisine culture="Asia">

		<!-- Indian Cuisine 1 -->
		<Cuisine cookingMethod="boiled">목살 스테이크 카레
			<Ingredients>
				<oilsAndFats>식용유
					<spoon>1</spoon>
					<gram>10</gram>
				</oilsAndFats>
			</Ingredients>
			<Ingredients cookingMethod="grilled">
				<meats classification="pork">목살
					<cup>1</cup>
					<gram>200</gram>
				</meats>
			</Ingredients>
			<Ingredients cookingMethod="stir-fried">
				<vegetables classification="root">양파
					<count>1</count>
					<gram>200</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">감자
					<count>1</count>
					<gram>150</gram>
				</vegetables>
			</Ingredients>
			<Ingredients>
				<vegetables classification="root">당근
					<count>1/4</count>
					<gram>70</gram>
				</vegetables>
			</Ingredients>
			<Ingredients cookingMethod="boiled">
				<water>물
					<cup>3.5</cup>
					<milliliter>665</milliliter>
				</water>
			</Ingredients>
			<Ingredients>
				<condiment classification="curry">카레
					<cup>1</cup>
					<gram>150</gram>
				</condiment>
			</Ingredients>			
			<Ingredients>
				<vegetables classification="lychee">피망
					<count>1/3</count>
					<gram>50</gram>
				</vegetables>
			</Ingredients>
		</Cuisine>
	</IndianCuisine>


	<ItalianCuisine culture="Europ">

		<!-- Italian Cuisine 1 -->
		<Cuisine cookingMethod="stir-fried">알리오올리오파스타
			<Ingredients>
				<water>물
					<cup>5</cup>
					<milliliter>1000</milliliter>
				</water>
			</Ingredients>
			<Ingredients>
				<condiment classification="salty">소금
					<spoon>1</spoon>
					<gram>10</gram>
				</condiment>
			</Ingredients>
			<Ingredients cookingMethod="boiled">
				<grain classification="wheat">파스타면
					<gram>100</gram>
				</grain>
			</Ingredients>
			<Ingredients>
				<oilsAndFats>올리브유
					<cup>1</cup>
					<milliliter>100</milliliter>
				</oilsAndFats>
			</Ingredients>
			<Ingredients cookingMethod="stir-fried">
				<vegetables classification="root">마늘
					<spoon>3</spoon>
					<gram>60</gram>
				</vegetables>
			</Ingredients>
